"""empty message

Revision ID: cd84e9125d05
Revises: d38a0e2b0ede
Create Date: 2020-11-07 21:47:37.852321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd84e9125d05'
down_revision = 'd38a0e2b0ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_at', sa.String(), nullable=True))
    op.drop_column('messages', 'sentAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sentAt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'sent_at')
    # ### end Alembic commands ###
