"""empty message

Revision ID: d38a0e2b0ede
Revises: dcd6562b6fa7
Create Date: 2020-11-07 21:04:02.606003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38a0e2b0ede'
down_revision = 'dcd6562b6fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sentAt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sentAt')
    # ### end Alembic commands ###
